from typing import Any, Callable, ContextManager, Iterable, Iterator

# Minimal stubs for functions and types used in the project

def set_page_config(*args: Any, **kwargs: Any) -> None: ...

def title(*args: Any, **kwargs: Any) -> None: ...

def write(*args: Any, **kwargs: Any) -> None: ...

def subheader(*args: Any, **kwargs: Any) -> None: ...

def markdown(*args: Any, **kwargs: Any) -> None: ...

def divider(*args: Any, **kwargs: Any) -> None: ...

def info(*args: Any, **kwargs: Any) -> None: ...

def success(*args: Any, **kwargs: Any) -> None: ...

def spinner(*args: Any, **kwargs: Any) -> ContextManager: ...

def chat_input(*args: Any, **kwargs: Any) -> Any: ...

def chat_message(role: str) -> Any: ...

def container() -> "Container": ...

class Container:
    def __enter__(self) -> "Container": ...
    def __exit__(self, *args: Any) -> None: ...
    def write(self, *args: Any, **kwargs: Any) -> None: ...


def columns(count: int): ...

class Columns(Iterable):
    def __iter__(self) -> Iterator[Any]: ...


def selectbox(*args: Any, **kwargs: Any) -> Any: ...

def button(*args: Any, **kwargs: Any) -> bool: ...

def expander(*args: Any, **kwargs: Any) -> ContextManager: ...

def switch_page(*args: Any, **kwargs: Any) -> None: ...

def metric(*args: Any, **kwargs: Any) -> None: ...

def text_input(*args: Any, **kwargs: Any) -> Any: ...

def slider(*args: Any, **kwargs: Any) -> Any: ...

def multiselect(*args: Any, **kwargs: Any) -> Any: ...

def cache_data(fn: Callable) -> Callable: ...

def cache_resource(fn: Callable) -> Callable: ...
